"""dd executor_id column

Revision ID: 201bbf9139a7
Revises: 39b784b863f6
Create Date: 2026-02-06 12:16:04.377378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '201bbf9139a7'
down_revision: Union[str, Sequence[str], None] = '39b784b863f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('executor_id', sa.Integer(), nullable=True))
    op.alter_column('tickets', 'author_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_foreign_key(None, 'tickets', 'users', ['executor_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.alter_column('tickets', 'author_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('tickets', 'executor_id')
    # ### end Alembic commands ###
