"""Add House model

Revision ID: 65829855565a
Revises: 72a7974b2fd9
Create Date: 2026-02-01 14:28:48.812753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65829855565a'
down_revision: Union[str, Sequence[str], None] = '72a7974b2fd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('houses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_houses_address'), 'houses', ['address'], unique=True)
    op.create_index(op.f('ix_houses_id'), 'houses', ['id'], unique=False)
    op.add_column('tickets', sa.Column('house_id', sa.Integer(), nullable=True))
    op.add_column('tickets', sa.Column('apartment', sa.String(), nullable=True))
    op.create_foreign_key(None, 'tickets', 'houses', ['house_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.drop_column('tickets', 'apartment')
    op.drop_column('tickets', 'house_id')
    op.drop_index(op.f('ix_houses_id'), table_name='houses')
    op.drop_index(op.f('ix_houses_address'), table_name='houses')
    op.drop_table('houses')
    # ### end Alembic commands ###
