"""Add specialty to user

Revision ID: a493fcc6c42f
Revises: cd3d3020c507
Create Date: 2026-02-03 18:28:02.674830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a493fcc6c42f'
down_revision: Union[str, Sequence[str], None] = 'cd3d3020c507'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('specialty', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'specialty')
    # ### end Alembic commands ###
